# authenticate user
POST http://dev.stormfm.io:3000/api/auth/login
Content-Type: application/json
{
  "identity": "terencege",
  "password": "password"
}

# create user
POST http://dev.stormfm.io:3000/api/users
Content-Type: application/json
{
  "username": "terenceg",
  "email": "terencegehui@yahoo.com",
  "password": "password"
}

# get user
GET http://dev.stormfm.io:3000/api/users/5804ac7840b9a7b9cb32c782