# hello
GET http://dev.stormfm.io:3000/api/hello

# authenticate user
POST http://dev.stormfm.io:3000/api/auth/login
Content-Type: application/json
{
  "identity": "terencege",
  "password": "password"
}

# create user
POST http://dev.stormfm.io:3000/api/users
Content-Type: application/json
{
  "username": "terencege4",
  "email": "terencegehui4@yahoo.com",
  "password": "password"
}

# get users
GET http://dev.stormfm.io:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MGFlZjRmMDRjMWNlMjkzNzFjMDk3MSIsImlhdCI6MTQ3NzM2MjUxMSwiZXhwIjoxNDc3Mzg0MTExfQ.LcgOIkmF72-lvy5htyeHpELntRbS53wrqaiBmhMOkDU

# get user
GET http://dev.stormfm.io:3000/api/users/580aef4f04c1ce29371c0971
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MGFlZjRmMDRjMWNlMjkzNzFjMDk3MSIsImlhdCI6MTQ3NzM2MjUxMSwiZXhwIjoxNDc3Mzg0MTExfQ.LcgOIkmF72-lvy5htyeHpELntRbS53wrqaiBmhMOkDU

# update user
PUT http://dev.stormfm.io:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MGFlZjRmMDRjMWNlMjkzNzFjMDk3MSIsImlhdCI6MTQ3NzE4OTcxNCwiZXhwIjoxNDc3MjExMzE0fQ.80RGP6-EjWUZUqNI_ZQwFLgVhogfmWo0PAJpcB0byIw
Content-Type: application/json
{
  "password": "password"
}

# delete user
DELETE http://dev.stormfm.io:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MGFmMzU5ZGFmMGNkMmE0MjgyZjYzZCIsImlhdCI6MTQ3NzExMzI4NSwiZXhwIjoxNDc3MTM0ODg1fQ.eObTjqTBXAuoHMruQhao0zvuK4olOWY7qb5_gr5VNso

# create track
POST http://dev.stormfm.io:3000/api/tracks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MGFlZjRmMDRjMWNlMjkzNzFjMDk3MSIsImlhdCI6MTQ3NzQxMzY2NywiZXhwIjoxNDc3NDM1MjY3fQ.rWBwt4WyX7OX_LWHR_Zt7Bl9hnl7TUo3j-LCM2FDG_U
Content-type: application/json
{
  "title": "Skin DeepJust Like Heaven",
  "artist": {
    "name": "Vincenzo feat. Minako"
  },
  "description": "Groovy deep house track from Arjunadeep artist Vincenzo.",
  "artwork": {
    "url": "https://i1.sndcdn.com/artworks-000091513345-7syibo-large.jpg"
  },
  "source": {
    "type": "soundcloud",
    "url": "https://soundcloud.com/anjunadeep/vincenzo-feat-minako-just-like-heaven-1"
  }
}

# get tracks
GET http://dev.stormfm.io:3000/api/tracks?page=8

# get track
GET http://dev.stormfm.io:3000/api/tracks/580b488128bd794b8cadecd9

# create like
POST http://dev.stormfm.io:3000/api/likes
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MGFlZjRmMDRjMWNlMjkzNzFjMDk3MSIsImlhdCI6MTQ3NzE4NDIwMywiZXhwIjoxNDc3MjA1ODAzfQ.YaOyXFEALgpvqbiQr3NKaCbSYSmGkp-oaWbW_QqM1NY
{
  "track_id": "580b488128bd794b8cadecd9"
}

# remove like
DELETE http://dev.stormfm.io:3000/api/likes
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MGFlZjRmMDRjMWNlMjkzNzFjMDk3MSIsImlhdCI6MTQ3NzE4NDIwMywiZXhwIjoxNDc3MjA1ODAzfQ.YaOyXFEALgpvqbiQr3NKaCbSYSmGkp-oaWbW_QqM1NY
{
  "track_id": "580b488128bd794b8cadecd9"
}
